### PR TITLE
added config file & remember window position & gradual audio decrease

### PR DESCRIPTION
**Pull request by zWolfrost**
-added config file at "~/.config/myxer/myxer.conf"
-added "remember last window position" option

Every option will get saved & loaded from the config file.

I'm kinda new to rust, hope that this PR respects your coding practices etc. (i have tried my best to do that).
If it doesn't, feel free to point out what you don't like about it.

I also found a little bug where if the audio source is stopped, the volume bar will get stuck on its last peak (this bug was also present previously) so if i manage to fix it i will open another PR for that.

### CODE REVIEW

**Comment by zWolfrost** [comment]
Never mind about the little bug, it somehow got fixed by itself (?) i can't seem to reproduce it anymore... I can't be mad about that.

**Comment by zWolfrost** [comment]
I have added a gradual decrease to freezed audio to fix the "little bug" i was talking about earlier. Also, it looks cool in my opinion. As always, if you don't like these features or only like some of them please feel free to tell me.

**Comment by zWolfrost** [comment]
This last commit fixes a bug where changing the "split channels" option makes the meters peaks full until they are refreshed by disabling and enabling the "visualize peaks" option. This is the last commit. I really hope this PR is not too overwhelming

**Comment by Aurailus** [comment]
Hi, thank you for taking your time to make this PR! The lack of settings saving and the peak visualizations not working when you change between split channels were both issues I was hoping to get to eventually, but unfortunately I've not had any time.

I'm happy to merge this is and publish a new release. Before I do though, you can add your name to the credits if you'd like. It's in `/src/about`.

**Comment by zWolfrost** [comment]
Hi, i have added my name, thank you for letting me.

**Comment by zWolfrost** [comment]
Hi, sorry for bothering you, but a month has passed and this PR has not seen any updates. I know you are busy with work, so I'm just making sure you remember about it, I'm not in an hurry or anything. If you want, i could maintain this project as well. Hope I'm not being too pushy :)

**Comment by Aurailus** [comment]
Hey, sorry about the delay. I'm taking 5 classes rn in uni, and I'm in the middle of finals period. I should have time to merge this in the next week or so. thanks for your patience.

**Comment by Aurailus** [comment]
Alright, I finally had a moment to check in on this properly. I've pulled the changes and ran them and they seem excellent! I'm going to publish a new release with these changes. Thank you so much!

**Pull request merged**
